// Captures browser operations before page scripts execute; it does not inspect DOM or own agent state.
export const native = {
  createElement: document.createElement.bind(document),
  elementsFromPoint: document.elementsFromPoint.bind(document),
  getComputedStyle: window.getComputedStyle.bind(window),
  scrollWindow: window.scrollBy.bind(window),
  postParent: window.parent.postMessage.bind(window.parent),
  randomUUID: crypto.randomUUID.bind(crypto),
  frame: window.requestAnimationFrame.bind(window),
  cancelFrame: window.cancelAnimationFrame.bind(window),
  rect: Element.prototype.getBoundingClientRect,
  WeakRef,
  weakDeref: WeakRef.prototype.deref as (this: WeakRef<Element>) => Element | undefined,
  MutationObserver,
  observeMutations: MutationObserver.prototype.observe,
  addListener: EventTarget.prototype.addEventListener,
  appendChild: Node.prototype.appendChild,
  attachShadow: Element.prototype.attachShadow,
  getAttribute: Element.prototype.getAttribute,
  matches: Element.prototype.matches,
  focusElement: HTMLElement.prototype.focus,
  setStyle: CSSStyleDeclaration.prototype.setProperty,
  scrollElement: Element.prototype.scrollBy as (this: Element, options: ScrollToOptions) => void,
  scrollIntoView: Element.prototype.scrollIntoView as (this: Element, options?: ScrollIntoViewOptions) => void,
  preventDefault: Event.prototype.preventDefault,
  stopImmediate: Event.prototype.stopImmediatePropagation,
  eventPath: Event.prototype.composedPath,
  portPost: MessagePort.prototype.postMessage,
  portStart: MessagePort.prototype.start,
  portClose: MessagePort.prototype.close,
};
